apiVersion: v1
kind: ConfigMap
metadata:
  name: __SERVICE__-config
  labels:
    app.kubernetes.io/name: __SERVICE__
data:
  LOG_LEVEL: "info"
  HTTP_BIND_ADDR: ":8080"
  EXAMPLE_PUBLIC_SETTING: "replace-me"
