apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: __NAMESPACE__

labels:
  - pairs:
      app.kubernetes.io/name: __SERVICE__
      app.kubernetes.io/part-of: __SERVICE__-platform

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pdb.yaml
  - hpa.yaml
  - deny-all.yaml
  - networkpolicy.yaml
  - internal-tls.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/__SERVICE__
    newTag: latest
