apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: __SERVICE__
  labels:
    app.kubernetes.io/name: __SERVICE__
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: __SERVICE__
