apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: __SERVICE__-deny-all
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: __SERVICE__
  policyTypes:
    - Ingress
    - Egress
