apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: __NAMESPACE__

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml
  - deny-all.yaml
  - networkpolicy.yaml
  - internal-tls.yaml

labels:
  - pairs:
      app.kubernetes.io/name: __SERVICE__
