apiVersion: v1
kind: ServiceAccount
metadata:
  name: __SERVICE__
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::__AWS_ACCOUNT__:role/__SERVICE__-pod-role
automountServiceAccountToken: false
